=== dataplumber/horizon/common/common-api/src/test/resources/mmr_fr.dtd
<!ELEMENT MMR_FR ( Entry_ID, 
                   File_Name, 
                   File_Release_Date,  
                   File_Version, 
                   Related_URL*,                   
                   Temporal_Coverage,  
                   Spatial_Coverage,
                   Personnel+,
	   Metadata_History,
	   File_Compression?
 )  >
 
<!-- DSD_Entry_ID (reference) ===================================== -->
<!ELEMENT Entry_ID (#PCDATA)>


<!ELEMENT File_Name  (#PCDATA)>
<!ELEMENT File_Release_Date (#PCDATA)>
<!ELEMENT File_Version (#PCDATA)>

<!-- Related URL ================================================= -->
<!ELEMENT Related_URL ( URL_Content_Type?,
                        URL+,
                        Description?
                      )
>

<!ELEMENT URL_Content_Type (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!-- Temporal Coverage =========================================== -->
<!ELEMENT Temporal_Coverage ( Start_Date?,
                              Start_Time?,
                              Stop_Date?,
                              Stop_Time?
                            )
>

<!ELEMENT Start_Date (#PCDATA)>
<!ELEMENT Start_Time (#PCDATA)>
<!ELEMENT Stop_Date (#PCDATA)>
<!ELEMENT Stop_Time (#PCDATA)>


<!-- Spatial Coverage ============================================ -->
<!ELEMENT Spatial_Coverage ( Southernmost_Latitude,
                             Northernmost_Latitude,
                             Westernmost_Longitude,
                             Easternmost_Longitude, 
                             Minimum_Altitude?,
                             Maximum_Altitude?,
                             Minimum_Depth?,
                             Maximum_Depth?
                           )
>

<!ELEMENT Southernmost_Latitude (#PCDATA) >
<!ELEMENT Northernmost_Latitude (#PCDATA) > 
<!ELEMENT Westernmost_Longitude (#PCDATA) > 
<!ELEMENT Easternmost_Longitude (#PCDATA) > 
<!ELEMENT Minimum_Altitude (#PCDATA) >
<!ELEMENT Maximum_Altitude (#PCDATA) > 
<!ELEMENT Minimum_Depth (#PCDATA) > 
<!ELEMENT Maximum_Depth (#PCDATA)>

<!-- Personnel =================================================== -->
<!ELEMENT Personnel ( Role+,
                      First_Name,
                      Middle_Name?,
                      Last_Name,
                      Email,
                      Phone,
                      Fax?,
                      Address
                    )
>

<!ELEMENT Role (#PCDATA)>
<!ELEMENT First_Name (#PCDATA)>
<!ELEMENT Middle_Name (#PCDATA)>
<!ELEMENT Last_Name (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Fax (#PCDATA)>
<!ELEMENT Address (#PCDATA)>

<!-- Metadata_History ================================================ -->
<!ELEMENT Metadata_History (FR_File_Version,
 			   FR_Creation_Date,
			    FR_Last_Revision_Date,
			    FR_Revision_History)>

<!--  Creation Date =========================================== -->
<!ELEMENT FR_File_Version (#PCDATA)>

<!-- Creation Date =========================================== -->
<!ELEMENT FR_Creation_Date (#PCDATA)>

<!-- Last Revision Date ====================================== -->
<!ELEMENT FR_Last_Revision_Date (#PCDATA)>

<!--  Revision History ======================================== -->
<!ELEMENT FR_Revision_History (#PCDATA)>

<!--  Compression ======================================== -->
<!ELEMENT File_Compression (#PCDATA)>

=== dataplumber/horizon/common/common-api/src/test/resources/FR-20070814-MODIS_T-JPL-L2P-T2007226164500.L2_LAC_GHRSST-v01.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE MMR_FR SYSTEM "mmr_fr.dtd"> 
<MMR_FR> 
<Entry_ID>JPL-L2P-MODIS_T</Entry_ID> 
<File_Name>20070814-MODIS_T-JPL-L2P-T2007226164500.L2_LAC_GHRSST-v01.nc</File_Name> 
<File_Release_Date>20070817T013548Z</File_Release_Date> 
<File_Version>1</File_Version> 
<Temporal_Coverage> 
<Start_Date>20070814T164508Z</Start_Date> 
<Stop_Date>20070814T165007Z</Stop_Date> 
</Temporal_Coverage> 
<Spatial_Coverage> 
<Southernmost_Latitude>-4.668</Southernmost_Latitude> 
<Northernmost_Latitude>16.146</Northernmost_Latitude> 
<Westernmost_Longitude>72.202</Westernmost_Longitude> 
<Easternmost_Longitude>97.034</Easternmost_Longitude> 
</Spatial_Coverage> 
<Personnel> 
<Role>Technical Contact</Role> 
<First_Name>Ed</First_Name> 
<Last_Name>Armstrong</Last_Name> 
<Email>ghrsst@podaac.jpl.nasa.gov</Email> 
<Phone>818-393-6710</Phone> 
<Fax>818-393-2718</Fax> 
<Address>Jet Propulsion Laboratory, 4800 Oak Grove Dr, Pasadena, CA 91109 USA</Address> 
</Personnel> 
<Metadata_History> 
<FR_File_Version>1</FR_File_Version> 
<FR_Creation_Date>20070817T013601Z</FR_Creation_Date> 
<FR_Last_Revision_Date>20070817T013601Z</FR_Last_Revision_Date> 
<FR_Revision_History>Quicklook MODIS L2P created at the GHRSST Global Data Assembly Center (GDAC), Fri Aug 17 01:36:01 2007</FR_Revision_History> 
</Metadata_History> 
<File_Compression>bzip</File_Compression> 
</MMR_FR>

=== dataplumber/horizon/common/common-api/src/test/resources/FR-20070828-GOES11-OSDPD-L2P-GOES11_North_0000Z-v01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MMR_FR SYSTEM "mmr_fr.dtd">
<MMR_FR>
  <Entry_ID>OSDPD-L2P-GOES11</Entry_ID>
  <File_Name>20070828-GOES11-OSDPD-L2P-GOES11_North_0000Z-v01.nc</File_Name>
  <File_Release_Date>20070828T011626Z</File_Release_Date>
  <File_Version>1.0</File_Version>
  <Related_URL>
    <URL>ftp://gp16.ssd.nesdis.noaa.gov/pub/goessst/L2P/20070828-GOES11-OSDPD-L2P-GOES11_North_0000Z-v01.nc.gz</URL>
    <Description>FTP directory containing GOES Level2p data</Description>
  </Related_URL>
  <Temporal_Coverage>
    <Start_Date>20070828T000000Z</Start_Date>
    <Stop_Date>20070828T001000Z</Stop_Date>
  </Temporal_Coverage>
  <Spatial_Coverage>
    <Southernmost_Latitude>  0.096</Southernmost_Latitude>
    <Northernmost_Latitude>76.204</Northernmost_Latitude>
    <Westernmost_Longitude>146.349</Westernmost_Longitude>
    <Easternmost_Longitude>-58.552</Easternmost_Longitude>
  </Spatial_Coverage>
  <Personnel>
    <Role>Technical Contact</Role>
    <First_Name>Eileen</First_Name>
    <Last_Name>Maturi</Last_Name>
    <Email>Eileen.Maturi@noaa.gov</Email>
    <Phone>301-763-8102 x172</Phone>
    <Fax>301-763-8572</Fax>
    <Address>NOAA/NESDIS/STAR/SOCD, 5200 Auth Road, WWB, RM 601 Camp Springs, MD 20746, USA</Address>
  </Personnel>
  <Metadata_History>
    <FR_File_Version>1.0</FR_File_Version>
    <FR_Creation_Date>20070828T011626Z</FR_Creation_Date>
    <FR_Last_Revision_Date>20070828T011626Z</FR_Last_Revision_Date>
    <FR_Revision_History>File created on 20070828T011626Z</FR_Revision_History>
  </Metadata_History>
  <File_Compression>gzip</File_Compression>
</MMR_FR>
